name: Deploy on Merge to main
on:
  push:
    branches:
      - main

jobs:
  get_deployment_id:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Create Deployment
        id: create_deployment
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          response=$(curl -s -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/marinhojess/checkly/deployments \
            -d '{"ref":"main","required_contexts": []}')
          deployment_id=$(echo "$response" | jq '.id')
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/marinhojess/checkly/deployments/$deployment_id/statuses \
            -d '{"environment":"production","state":"success","log_url":"https://example.com/deployment/42/output","description":"Deployment finished successfully."}'
