name: Deploy Github API
on:
  push:
    branches:
      - main
      - develop
jobs:
  deploy-staging:
    if: github == 'refs/heads/develop'
    runs-on: ubuntu-latest
    environment:
      name: Staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Staging Deployment
        id: staging_deployment
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          response=$(curl -s -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/marinhojess/checkly/deployments \
            -d '{"environment": "Staging","ref": "main","required_contexts": []}')
          deployment_id=$(echo "$response" | jq '.id')
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/marinhojess/checkly/deployments/$deployment_id/statuses \
            -d '{"environment":"Staging","state":"success","environment_url": "https://teste-staging.com","description":"Deployment finished successfully."}'
  deploy-production:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    #needs: deploy-staging
    environment:
      name: Production
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Production Deployment
        id: production_deployment
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          response=$(curl -s -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/marinhojess/checkly/deployments \
            -d '{"environment": "Production","ref": "main","required_contexts": []}')
          deployment_id=$(echo "$response" | jq '.id')
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/marinhojess/checkly/deployments/$deployment_id/statuses \
            -d '{"environment":"Production","state":"success","environment_url": "https://teste-production.com","description":"Deployment finished successfully."}'
